"""
Entry Engine — The "Holy Grail" Execution Logic
-------------------------------------------------
Implements the core entry criteria for AuraTrade across both regimes:

    1. Price sweeps/reclaims a major level (London H/L or Prev NYAM H/L)
    2. Creates a Fair Value Gap (FVG) through displacement (3-candle pattern)
    3. Entry ONLY on retest/fill of that FVG
    4. VWAP alignment = maximum confidence

Supports pyramiding in BLUE regime and "Remove Quickly" exits via 9-EMA.
"""

import logging
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any
from datetime import datetime
import pandas as pd
import numpy as np

import config
from fvg_detector import FVG, detect_fvg, is_fvg_filled, is_fvg_rejected, get_nearest_active_fvg
from risk_guard import RiskGuard

logger = logging.getLogger(__name__)


@dataclass
class EntrySignal:
    """Complete entry instruction generated by the engine."""
    direction: str                      # "long" or "short"
    confidence: float                   # 0.0 … 1.0
    entry_price: float
    stop_loss: float
    target: float
    reason: str                         # Human-readable explanation
    contracts: int
    fvg_mid: float                      # Reference FVG midpoint
    regime: str                         # "BLUE" or "RED"
    pyramid: bool = False               # Is this a pyramid add?
    timestamp: datetime = field(default_factory=datetime.now)

    @property
    def risk_ticks(self) -> float:
        return abs(self.entry_price - self.stop_loss)

    @property
    def reward_ticks(self) -> float:
        return abs(self.target - self.entry_price)

    @property
    def rr_ratio(self) -> float:
        if self.risk_ticks == 0:
            return 0.0
        return round(self.reward_ticks / self.risk_ticks, 2)


@dataclass
class ActivePosition:
    """Tracks an open position for pyramiding and remove-quickly checks."""
    direction: str
    entry_price: float
    stop_loss: float
    initial_target: float
    contracts: int
    entry_time: datetime
    regime_at_entry: str
    fvg_reference: Optional[FVG] = None
    pyramid_count: int = 0
    max_pyramids: int = 1            # BLUE allows 1 pyramid
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0

    @property
    def is_long(self) -> bool:
        return self.direction == "long"

    @property
    def is_short(self) -> bool:
        return self.direction == "short"

    def current_r_multiple(self, current_price: float, tick_value: float = 0.5) -> float:
        """Return current profit as multiple of initial risk (R)."""
        risk = abs(self.entry_price - self.stop_loss)
        if risk == 0:
            return 0.0
        if self.is_long:
            move = current_price - self.entry_price
        else:
            move = self.entry_price - current_price
        return round(move / risk, 2)


# ═══════════════════════════════════════════════════════════════════════════════
#  HOLY GRAIL EVALUATION
# ═══════════════════════════════════════════════════════════════════════════════

def evaluate_entry(
    price_data: pd.DataFrame,
    vwap: float,
    ema9: float,
    regime: str,
    active_position: Optional[ActivePosition],
    key_levels: Dict[str, float],
    product: str = "MNQ",
    risk_guard: Optional[RiskGuard] = None,
) -> Optional[EntrySignal]:
    """
    The core "Holy Grail" entry evaluator.

    Steps
    -----
    1. Check level reclaim / sweep (liquidity grab then reversal)
    2. Check FVG formation with sufficient displacement
    3. Check if retest / fill of that FVG is in progress NOW
    4. Confirm VWAP alignment (price & FVG on same side of VWAP as direction)
    5. Apply regime-appropriate filters
    6. Return EntrySignal or None

    Parameters
    ----------
    price_data : pd.DataFrame
        OHLC DataFrame ending at current bar. Must include at least 30 bars.
    vwap : float
        Current VWAP value.
    ema9 : float
        Current 9-EMA value.
    regime : str
        "BLUE" or "RED"
    active_position : ActivePosition or None
        If present, engine may evaluate pyramiding instead of new entry.
    key_levels : dict
        {level_name: price, ...} e.g. London_High, London_Low, etc.
    product : str
        "MNQ" or "MES"
    risk_guard : RiskGuard or None
        Used to check if pyramiding is allowed under current risk limits.

    Returns
    -------
    EntrySignal or None
    """
    if price_data.empty or len(price_data) < 20:
        logger.debug("Insufficient bars for entry evaluation.")
        return None

    latest = price_data.iloc[-1]
    close = float(latest["close"])
    low = float(latest["low"])
    high = float(latest["high"])

    # ── 0. Detect all FVGs ─────────────────────────────────────────────────
    all_fvgs = detect_fvg(price_data)
    if not all_fvgs:
        return None

    # ── 1. Check for level sweep / reclaim ─────────────────────────────────
    sweep_info = _detect_level_sweep_and_reclaim(price_data, key_levels)
    if not sweep_info:
        logger.debug("No level sweep/reclaim detected. ENTRY BLOCKED — Reclaim is mandatory for all regimes.")
        return None

    # ── 2. Find FVGs aligned with sweep (or recent virgin FVGs) ──────────
    direction_needed = sweep_info.get("direction", None) if sweep_info else None

    candidate_fvgs = _filter_candidate_fvgs(
        all_fvgs,
        price_data,
        vwap,
        close,
        regime,
        direction_needed,
    )
    if not candidate_fvgs:
        logger.debug("No candidate FVGs passed filters.")
        return None

    # ── 3. Check if we are AT the retest right now ─────────────────────────
    best_fvg = None
    retest_confidence = 0.0

    for fvg in candidate_fvgs:
        is_retesting = _is_currently_retesting(close, low, high, fvg)
        if is_retesting:
            # Compute confidence based on confluence
            conf = _compute_entry_confidence(
                fvg=fvg,
                vwap=vwap,
                ema9=ema9,
                close=close,
                sweep_info=sweep_info,
                regime=regime,
                price_data=price_data,
            )
            if conf > retest_confidence:
                retest_confidence = conf
                best_fvg = fvg

    if best_fvg is None or retest_confidence < 0.55:
        logger.debug("No valid retest in progress or confidence too low.")
        return None

    # ── 4. Compute stop, target, position size ─────────────────────────────
    signal = _build_entry_signal(
        fvg=best_fvg,
        close=close,
        vwap=vwap,
        ema9=ema9,
        regime=regime,
        confidence=retest_confidence,
        sweep_info=sweep_info,
        product=product,
    )

    # ── 5. Pyramiding check (BLUE only) ────────────────────────────────────
    if active_position is not None and regime == "BLUE":
        pyramid = evaluate_pyramid(active_position, price_data, all_fvgs, regime, risk_guard)
        if pyramid:
            signal.pyramid = True
            signal.contracts = min(
                signal.contracts,
                config.MAX_CONTRACTS_MNQ - active_position.contracts
            )
            if signal.contracts <= 0:
                return None
            signal.reason = f"[PYRAMID] {signal.reason}"

            # Mutate existing position in place (do NOT create new ActivePosition)
            old_contracts = active_position.contracts
            new_contracts = signal.contracts
            total_contracts = old_contracts + new_contracts

            # Blended average entry price
            active_position.entry_price = round(
                (active_position.entry_price * old_contracts + signal.entry_price * new_contracts)
                / total_contracts, 2
            )
            active_position.contracts = total_contracts
            active_position.pyramid_count += 1

            # Track original stop: keep the most conservative (tightest) stop
            if active_position.is_long:
                active_position.stop_loss = max(active_position.stop_loss, signal.stop_loss)
            else:
                active_position.stop_loss = min(active_position.stop_loss, signal.stop_loss)

            # Update FVG reference to the newest one
            active_position.fvg_reference = best_fvg

    logger.info(
        f"ENTRY SIGNAL | {signal.direction.upper()} | conf={signal.confidence:.0%} | "
        f"entry={signal.entry_price} | stop={signal.stop_loss} | target={signal.target} | "
        f"R:R={signal.rr_ratio} | {signal.reason}"
    )
    return signal


# ═══════════════════════════════════════════════════════════════════════════════
#  PYRAMIDING LOGIC
# ═══════════════════════════════════════════════════════════════════════════════

def evaluate_pyramid(
    active_position: ActivePosition,
    price_data: pd.DataFrame,
    fvg_list: List[FVG],
    regime: str,
    risk_guard: Optional[RiskGuard] = None,
) -> bool:
    """
    BLUE regime only: add to winners if:
        • First trade is profitable by at least 1R
        • A second FVG forms in the SAME direction
        • Max contracts not exceeded
        • Risk guard allows additional trade

    Parameters
    ----------
    active_position : ActivePosition
    price_data : pd.DataFrame
    fvg_list : List[FVG]
    regime : str
    risk_guard : RiskGuard or None

    Returns
    -------
    bool
    """
    if regime != "BLUE":
        return False
    if active_position.pyramid_count >= active_position.max_pyramids:
        return False

    # Risk guard check: do not pyramid if risk limits are breached
    if risk_guard is not None and not risk_guard.can_trade():
        logger.debug("Pyramid rejected: risk_guard.can_trade() is False.")
        return False

    current_price = float(price_data.iloc[-1]["close"])
    r_multiple = active_position.current_r_multiple(current_price)

    # Must be at least +1R in profit
    if r_multiple < config.PYRAMID_MIN_PROFIT_R:
        logger.debug(f"Pyramid rejected: only {r_multiple:.2f}R profit (< {config.PYRAMID_MIN_PROFIT_R}R)")
        return False

    # Look for a second FVG in same direction, newer than position entry
    direction = "bullish" if active_position.is_long else "bearish"
    entry_time = active_position.entry_time

    newer_fvgs = [
        f for f in fvg_list
        if f.direction == direction
        and f.created_at > entry_time
        and not f.filled
    ]

    if not newer_fvgs:
        logger.debug("Pyramid rejected: no new same-direction FVG found.")
        return False

    # Check if we're currently retesting the newest FVG
    latest = price_data.iloc[-1]
    close = float(latest["close"])
    low = float(latest["low"])
    high = float(latest["high"])

    for fvg in sorted(newer_fvgs, key=lambda x: x.created_at, reverse=True):
        if _is_currently_retesting(close, low, high, fvg):
            logger.info(f"Pyramid approved: {direction} FVG retest at {fvg.mid()}, current R={r_multiple:.2f}")
            # Increment pyramid count BEFORE returning True
            active_position.pyramid_count += 1
            return True

    return False


# ═══════════════════════════════════════════════════════════════════════════════
#  REMOVE QUICKLY — 9-EMA EXIT
# ═══════════════════════════════════════════════════════════════════════════════

def should_remove_quickly(position: ActivePosition, price_data: pd.DataFrame, ema9: float) -> bool:
    """
    Close position immediately if price closes on opposite side of 9-EMA.

    Parameters
    ----------
    position : ActivePosition
    price_data : pd.DataFrame
        Must have 'close' column for latest bar.
    ema9 : float
        Current 9-EMA value.

    Returns
    -------
    bool
    """
    if price_data.empty:
        return False
    close_price = float(price_data.iloc[-1]["close"])

    if position.is_long and close_price < ema9:
        logger.warning(f"REMOVE QUICKLY: Long closed — close {close_price} < EMA9 {ema9}")
        return True
    if position.is_short and close_price > ema9:
        logger.warning(f"REMOVE QUICKLY: Short closed — close {close_price} > EMA9 {ema9}")
        return True
    return False


# ═══════════════════════════════════════════════════════════════════════════════
#  INTERNAL HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

def _detect_level_sweep_and_reclaim(
    price_data: pd.DataFrame,
    key_levels: Dict[str, float],
    lookback: int = 10,
) -> Optional[Dict[str, Any]]:
    """
    Detect if price recently swept a major level then reclaimed it.
    Returns dict with 'direction', 'level_name', 'level_price' or None.
    """
    if not key_levels or len(price_data) < lookback + 3:
        return None

    recent = price_data.tail(lookback + 3)
    latest_close = float(price_data.iloc[-1]["close"])

    # London levels are primary; fallback to pre-market / prev session
    priority = ["London_High", "London_Low", "Prev_NYAM_High", "Prev_NYAM_Low",
                "PreMarket_High", "PreMarket_Low", "Prev_Session_High", "Prev_Session_Low"]

    for level_name in priority:
        if level_name not in key_levels:
            continue
        level_price = float(key_levels[level_name])

        # Check for sweep above level (high pokes above, then close below)
        if "High" in level_name:
            swept = (recent["high"].max() >= level_price * 0.999)
            reclaimed = latest_close < level_price
            if swept and reclaimed:
                return {
                    "direction": "short",
                    "level_name": level_name,
                    "level_price": level_price,
                    "type": "sweep_high_reclaim_below",
                }

        # Check for sweep below level (low pokes below, then close above)
        if "Low" in level_name:
            swept = (recent["low"].min() <= level_price * 1.001)
            reclaimed = latest_close > level_price
            if swept and reclaimed:
                return {
                    "direction": "long",
                    "level_name": level_name,
                    "level_price": level_price,
                    "type": "sweep_low_reclaim_above",
                }

    return None


def _filter_candidate_fvgs(
    fvgs: List[FVG],
    price_data: pd.DataFrame,
    vwap: float,
    close: float,
    regime: str,
    direction_needed: Optional[str],
) -> List[FVG]:
    """
    Filter FVGs based on:
      • Not too old
      • VWAP alignment (same side as direction)
      • Regime direction bias
      • Displacement size
    """
    candidates = []

    for fvg in fvgs:
        # Age check
        if fvg.age_bars > config.FVG_MAX_AGE_BARS:
            continue
        if fvg.filled:
            continue

        # Minimum height
        if fvg.height_ticks() < config.FVG_MIN_DISPLACEMENT_TICKS:
            continue

        # Direction filter from sweep
        if direction_needed:
            if fvg.is_bullish and direction_needed != "long":
                continue
            if not fvg.is_bullish and direction_needed != "short":
                continue

        # VWAP alignment
        if fvg.is_bullish:
            # Bullish FVG should be AT or ABOVE VWAP for longs
            vwap_ok = fvg.bottom >= vwap * 0.998
        else:
            # Bearish FVG should be AT or BELOW VWAP for shorts
            vwap_ok = fvg.top <= vwap * 1.002

        if not vwap_ok:
            continue

        # ═══════════════════════════════════════════════════════════════════════
        #  NON-NEGOTIABLE VWAP FILTER — BLUE REGIME ONLY
        #  Blue days: ONLY long above VWAP, ONLY short below VWAP
        # ═══════════════════════════════════════════════════════════════════════
        if regime == "BLUE":
            if fvg.is_bullish and close <= vwap:
                logger.debug(f"BLUE VWAP FILTER: Bullish FVG rejected — close {close} <= VWAP {vwap}")
                continue
            if not fvg.is_bullish and close >= vwap:
                logger.debug(f"BLUE VWAP FILTER: Bearish FVG rejected — close {close} >= VWAP {vwap}")
                continue

        # Regime-specific filters
        if regime == "RED":
            # In RED we need a failed breakout / trap — stricter on FVG quality
            if fvg.height_ticks() < config.FVG_MIN_DISPLACEMENT_TICKS + 2:
                continue

        candidates.append(fvg)

    return candidates


def _is_currently_retesting(close: float, low: float, high: float, fvg: FVG) -> bool:
    """Check if current bar is interacting with the FVG zone."""
    # Price has entered or is touching the FVG
    if fvg.is_bullish:
        # For bullish: price drops into the zone (low <= top and close near zone)
        return low <= fvg.top and close >= fvg.bottom
    else:
        # For bearish: price rallies into the zone (high >= bottom and close near zone)
        return high >= fvg.bottom and close <= fvg.top


def _compute_entry_confidence(
    fvg: FVG,
    vwap: float,
    ema9: float,
    close: float,
    sweep_info: Optional[Dict],
    regime: str,
    price_data: pd.DataFrame,
) -> float:
    """
    Compute a 0.0–1.0 confidence score for this entry setup.
    Higher = stronger confluence.
    """
    score = 0.5  # Base score

    # 1. Sweep/reclaim confluence (+0.20)
    if sweep_info is not None:
        score += 0.20
        if sweep_info.get("level_name", "").startswith("London"):
            score += 0.05  # London levels are highest quality

    # 2. VWAP alignment (+0.15)
    if fvg.is_bullish and fvg.bottom > vwap:
        score += 0.15
    elif not fvg.is_bullish and fvg.top < vwap:
        score += 0.15
    else:
        score += 0.08  # Partial alignment

    # 3. EMA9 alignment (+0.10)
    if fvg.is_bullish and close > ema9:
        score += 0.10
    elif not fvg.is_bullish and close < ema9:
        score += 0.10

    # 4. FVG size quality (+0.05 to +0.10)
    ht = fvg.height_ticks()
    if ht >= 8:
        score += 0.10
    elif ht >= 6:
        score += 0.07
    elif ht >= 4:
        score += 0.05

    # 5. Regime alignment bonus
    if regime == "BLUE" and fvg.is_bullish:
        score += config.REGIME_CONTEXT["BLUE"]["confidence_boost"]
    elif regime == "RED" and not fvg.is_bullish:
        score += config.REGIME_CONTEXT["RED"]["confidence_boost"]

    # 6. Recency penalty (older FVGs slightly less reliable)
    age_penalty = min(0.10, fvg.age_bars / 200)
    score -= age_penalty

    return round(max(0.0, min(1.0, score)), 3)


def _build_entry_signal(
    fvg: FVG,
    close: float,
    vwap: float,
    ema9: float,
    regime: str,
    confidence: float,
    sweep_info: Optional[Dict],
    product: str = "MNQ",
) -> EntrySignal:
    """
    Construct the final EntrySignal with stop, target, and sizing.
    """
    direction = "long" if fvg.is_bullish else "short"

    # Entry price: midpoint of FVG zone for limit entry
    entry_price = fvg.mid()

    # Stop loss: below FVG / below recent swing for longs (and vice versa)
    if direction == "long":
        stop_loss = fvg.bottom - (config.STOP_BUFFER_TICKS * config.TICK_SIZE_MNQ)
    else:
        stop_loss = fvg.top + (config.STOP_BUFFER_TICKS * config.TICK_SIZE_MNQ)

    # Target: regime-dependent R-multiple
    if regime == "BLUE":
        target_r = config.TARGET_R_DEFAULT
    else:
        target_r = config.TIGHT_TARGET_R_RED

    risk = abs(entry_price - stop_loss)
    if direction == "long":
        target = entry_price + (risk * target_r)
    else:
        target = entry_price - (risk * target_r)

    # Sizing: max contracts for product
    contracts = config.get_max_contracts(product)

    # Build human-readable reason
    parts = [f"Holy Grail {direction.upper()}"]
    if sweep_info:
        parts.append(f"sweep of {sweep_info['level_name']}@{sweep_info['level_price']}")
    parts.append(f"FVG {fvg.direction} [{fvg.bottom:.2f}-{fvg.top:.2f}]")
    parts.append(f"VWAP={vwap:.2f} EMA9={ema9:.2f}")
    parts.append(f"conf={confidence:.0%}")

    reason = " | ".join(parts)

    return EntrySignal(
        direction=direction,
        confidence=confidence,
        entry_price=round(entry_price, 2),
        stop_loss=round(stop_loss, 2),
        target=round(target, 2),
        reason=reason,
        contracts=contracts,
        fvg_mid=round(fvg.mid(), 2),
        regime=regime,
    )
